version: '3'

services:
  db:
    image: mariadb:10.5
    container_name: db
    restart: unless-stopped
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
    env_file: .env
    environment:
      - MYSQL_DATABASE=gichool
    networks:
      - app-network
    volumes:
      - mydata:/var/lib/mysql
    ports:
      - '33061:3306' # 배포시 3306으로 수정

  wordpress:
    depends_on: 
      - db
    image: 222.112.48.9:5000/gichool:0.0.2
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=gichool
    volumes:
      - mywordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.19.0-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - mywordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - mywordpress:/var/www/html     
    command: certonly --webroot --webroot-path=/var/www/html --email devmoonho@gmail.com --agree-tos --no-eff-email --staging -d gichoolfactory.com -d www.gichoolfactory.com   

volumes:
  mydata:      
  mywordpress:
  certbot-etc:

networks:
  app-network:
    driver: bridge  